# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5e77c1c339730ff6439762932eb5e6be2b6a86f707245b34be049754414d923f43e0b18cdb43b788e0856918c9e557f7b5a3440e2f6a91d4b9d522325b5e8d8

test:
  secret_key_base: b20bff25889ebbefb561f8dbc21f42592f65b0ee24909a433ae2a45f0a51ce510d407a36e2c8ab659167740c0888952debeb49152e7b0916108186c5d87cfbbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
